### ISSUE TITLE
Update Dependencies (Renovate Bot)

### ISSUE THREAD

**Issue by Trim21** [Trim21/BGmi-NG#1]
This [master issue](https://renovatebot.com/blog/master-issue) contains a list of Renovate updates and their statuses.

## Awaiting Schedule

These updates are awaiting their schedule. Click on a checkbox to ignore the schedule.
 - [ ] build(deps): update dependency stevedore to v2

## Open

These updates have all been created already. Click a checkbox below to force a retry/rebase of any.

 - [ ] [build(deps): update dependency sphinx to v3.0.4](../pull/11)
 - [ ] [build(deps): update dependency trim21/azure-pipeline-templates to v0.0.8](../pull/12)
 - [ ] [build(deps-dev): update deps-dev](../pull/13) (`mypy`, `pytest`, `pytest-mock`)
 - [ ] **Check this option to rebase all the above open PRs at once**

**Comment by Trim21** [comment]
```yaml
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.7.0
    hooks:
      - id: blacken-docs
        additional_dependencies:
          # renovate: pypi
          - black==19.3b0
```
